[tool.poetry]
name = "ka-ching"
version = "0.1.0"
description = ""
authors = ["Rudraprasad Das <brayn003@gmail.com>"]
packages = [
    { include = "services", from = "." }
]

[tool.poetry.dependencies]
python = "^3.12"
pymongo = "^4.6.2"
python-dotenv = "^1.0.1"
pytz = "^2024.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
