name: Build and push

on:
  push:
    branches: 
    - main

jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
      tick-workers: ${{ steps.filter.outputs.tick-workers }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
            tick-workers:
              - 'tick-workers/**'

  build-server:
    name: build-server
    needs: path-filter
    if: needs.path-filter.outputs.server == 'true'
    uses: ./.github/workflows/build-and-push-server.yml
    secrets: inherit
    with:
      pr: ${{ github.event.pull_request.number }}
