name: Build client

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ORG }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:client"
          platforms: linux/amd64,linux/arm64
          tags: client
      - name: Save image
        run: docker save client | gzip > client.tar.gz
      - name: Upload image
        uses: actions/cache/save@v3
        with:
          path: client.tar.gz
          key: image-client-${{github.run_id}}

