name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      server--release_created: ${{ steps.release.outputs.server--release_created }}
      client--release_created: ${{ steps.release.outputs.client--release_created }}
      tick-workers--release_created: ${{ steps.release.outputs.tick-workers--release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
  
  release-server:
    needs: release-please
    if: ${{ needs.release-please.outputs.server--release_created }}
    uses: brayn003/stonk.ninja/.github/workflows/release-server.yaml@main

  release-client:
    needs: release-please
    if: ${{ needs.release-please.outputs.client--release_created }}
    uses: brayn003/stonk.ninja/.github/workflows/release-client.yaml@main

  release-tick-workers:
    needs: release-please
    if: ${{ needs.release-please.outputs.tick-workers--release_created }}
    uses: brayn003/stonk.ninja/.github/workflows/release-tick-workers.yaml@main
