name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4

      - run: echo "Release created ${{ steps.release.outputs.release_created }}"
        if: ${{ steps.release.outputs.release_created }}
