name: Release server

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get release manifest
        id: release-manifest
        run: |
          REPO=${{ github.repository }}
          RELEASE_MANIFEST=$(wget https://raw.githubusercontent.com/$REPO/main/.release-please-manifest.json -q -O -)
          VERSION=$(jq -r '.server' <<< "${RELEASE_MANIFEST}")
          echo "version=${VERSION}" >> ">> $GITHUB_OUTPUT"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_ORG }}/stonk.ninja-tick-workers:latest
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=${{ steps.release-manifest.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release-manifest.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.release-manifest.outputs.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ORG }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
