apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  namespace: {{ .Values.clusterIssuer.namespace }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acmeServer }}
    email: {{ .Values.clusterIssuer.acmeEmail }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
